### ISSUE TITLE
Transmitter battery

### ISSUE THREAD

**Issue by SamuelAlinder** [StephenBlackWasAlreadyTaken/xDrip-Experimental#168]
Hello.. I installed the latest beta version at the same time as I changed the transmitter.. Running an xDrip (not share), and everything works except it keeps saying Transmitter battery very low on the phone.. If I go into the status menu it says Transmitter battery - OK

Any ideas on how to get rid of the message?

/Samuel

**Comment by AdrianLxM** [comment]
The message is shown in the background of the chart if the threshold was once passed during the sensor session. The number in the system status is the one last sent from the transmitter (i.e. from the last 5 minutes if not out of range). While getting lower, the battery may have times it recovers - this is why it is possible to see a higher number in the system status. It usually won't take long to show a lower numbers again.

The message will stay in the background until a new sensor session is started. We chose to do so that parents will see it. A simple alarm while the phone is with the kid at school would just annoy, be dismissed and never seen by a parent.

In your case I presume, you hot-swapped the transmitters and kept the sensor session alive?
There's not much you can do but sitting it out. With the next sensor change the issue should resolve itself. (If not, please report!)
Stopping and restarting the sensor session of course would also delete the message, but you would loose all the calibration data as well.

(Sorry for the long answer - I'd like to have it as sort of documentation)

**Comment by SamuelAlinder** [comment]
Actually no.. I Changed the transmitter, and after that I renistalled the phone to the latest version.. So that cannot be the case here.. I was running an older self compiled version before.. (probably 1.5 years old)
And new sensor.. no hotswap..

**Comment by AdrianLxM** [comment]
Hm strange. Would you mind exporting your xDrip-Database (Menu-Button -> Export database) and send it to me: adrian.m@inbox.com ?

**Comment by AdrianLxM** [comment]
@mayaalinder, thanks for the DB.
Quite at the beginning (12th packet) there was a packet with battery level 21. It's the only one with a low value. I cannot say if something went wrong with the transmission, or if the old empty transmitter still had something to say (unlikely if you just have don't have a "catch all" firmware on the wixel).

Does it help you, that I'm pretty sure it will go away with the next sensor?

**Comment by swissalpine** [comment]
Same here.
Yesterday I changed the transmitter (and flashed the Wixel) without changing the sensor, but the warning "transmitter battery very low" is still there. 
In System Status I read: Transmitter Battery: 215 - ok

**Comment by AdrianLxM** [comment]
@swissalpine, did you hotswap the transmitter without stopping/starting the sensor session in the xDrip-App?

**Comment by swissalpine** [comment]
Yes. I did.

**Comment by AdrianLxM** [comment]
@swissalpine, the warning on the main screen depends on the lowest battery value for the current sensor session. It should go away, once you start a new sensor.
Please report back if it doesn't.

Viele Grüße

**Comment by swissalpine** [comment]
It's a bug or a feature? ;-)

**Comment by SamuelAlinder** [comment]
Hmm.. this keeps coming back even though i have a new battery..
