### ISSUE TITLE
Unstable BT + Wifi Wixel

### ISSUE THREAD

**Issue by christerjensen** [StephenBlackWasAlreadyTaken/xDrip-Experimental#280]
@tzachi-dar made some timing improvements half a year ago - se old closed issue "Unstable Wifi Wixel #162"'

Setup: 2 RPis with Wixels in house + Samsung S3 with wixel and hm11. xDrip with BT+Wifi setup. Wifi + mobile data always on.

We have been running rock solid with Wifi and BT on my daughters phone with Tzachi-dars code, but last week we updated to xDrip Experimental 2 Beta 5_1. Started getting the same gaps in captured values with BT. All fine inside house when the phone gets values from RPIs. 

When she leaves house for kindergarten we get 1-3 missed packets an hour. The packets are captured by the Wixel (quite sure since it stops blinking) - but they are not in xDrip (also tested this at home when I entered fake IPs for RPIs). 

Previously we used Dexterity - in issue #162 the values were hidden somewhere in the database (an export and re-import showed the missing values). 

I'm not quite sure if Tzachi-dars improvements were actually merged into the new Beta 5? Guess this only is relevant for those running BT+Wifi (few?)

Last few days we've been running xDrip+ from @jamorham, same error there, but syncs nice to the xDrip+ app on my phone (I can now do calibrations from my phone). 

![xdrip2_05](https://cloud.githubusercontent.com/assets/11073675/13108219/ff7858ec-d571-11e5-8ae5-775aef70457e.jpg)

**Comment by jamorham** [comment]
Does this problem only occur when you have the `Wifi Wixel + BT Wixel` data source mode enabled?

If you switch to `Bluetooth Wixel` does the problem disappear?

**Comment by christerjensen** [comment]
I think it also happens when only Bluetooth Wixel is enabled (did some quick testing yesterday). I can enable Bluetooth Wixel only and turn of Wifi in kindergarten tomorrow. 

I will also export the database from the xDrip app and see if the values are hidden somewhere (last time they suddenly appeared with an export/re-import).

**Comment by jamorham** [comment]
If the problem occurs when only in Bluetooth mode then based on the previous issue I assume it is to do with wake-locks in the bluetooth code.

I am not that familiar with recent changes in that area but I thought some reworking had been done to support android 6 which might affect things. Any thoughts @AdrianLxM @tzachi-dar ?

**Comment by tzachi-dar** [comment]
Hi,

My changes are in the latest beta. In any case, things are indeed related
to BT and not to wifi.

Please do the experiment that Jamorham has suggested and will see if it
helps or not.

In the case that it does not, I'll try to see what has changed from the old
code.

You can also try and run dexterity on your phone and see if this solves the
problem.

Thanks
Tzachi

**Comment by Fredensvold** [comment]
Had my daughter wear the phone with only BT capture - same problem (tested 2 hours).
I then installed Dexterity - used Wifi capture with 127.0.0.1:50005. Dexterity also missed 1-2 packets an hour. The strange thing is that Dexterity reports her Transmitter ID as 6AKMR - it is close, but only the first and last is correct. I've flashed a few different firmwares on the Wixel, they behave the same (Jamorhams, xdripkit and last xdrip-wixel from stephen - It is stephens on it now, the ID entered in dexdrip.c is correct and it is setup to only listen to her Dexcom sensor)

Exported the database - packets are missing. Quite sure the Wixel captures the data since it flashes for a few seconds every 5 minutes. 

It seemed quite similar to the #162 issue, but the difference is that Dexterity captured packets then but they were not transferred to xDrip app. Really strange - I have a feeling it could be the HM11 dropping BT connection to the phone (nothing changed on the phone). The Dexcom unit has collected all packets so the transmitter must be fine.

I'll close this issue tomorrow.

**Comment by christerjensen** [comment]
Had my daughter wear the phone with only BT capture - same problem (tested 2 hours).
I then installed Dexterity - used Wifi capture with 127.0.0.1:50005. Dexterity also missed 1-2 packets an hour. The strange thing is that Dexterity reports her Transmitter ID as 6AKMR - it is close, but only the first and last is correct. I've flashed a few different firmwares on the Wixel, they behave the same (Jamorhams, xdripkit and last xdrip-wixel from stephen - It is stephens on it now, the ID entered in dexdrip.c is correct and it is setup to only listen to her Dexcom sensor)

Exported the database - packets are missing. Quite sure the Wixel captures the data since it flashes for a few seconds every 5 minutes. 

It seemed quite similar to the #162 issue, but the difference is that Dexterity captured packets then but they were not transferred to xDrip app. Really strange - I have a feeling it could be the HM11 dropping BT connection to the phone (nothing changed on the phone). The Dexcom unit has collected all packets so the transmitter must be fine.

I'll close this issue tomorrow.
